In [1]:
import numpy as np 
import pandas as pd 
from os import listdir
from shutil import copy2 


# Pandas setup
pd.set_option('display.max_columns', 1000)
pd.set_option('display.max_rows', 1000) 
pd.set_option('display.max_colwidth', -1)

In [2]:
path = "./Dataset/"
word = "fosforo"
archives = listdir(path) 

matches = [value for value in archives if word in value]
matches = sorted(matches)
matches

['fosforo_2013.csv',
 'fosforo_2014.csv',
 'fosforo_2015.csv',
 'fosforo_2016.csv',
 'fosforo_2017.csv',
 'fosforo_2018.csv',
 'fosforo_2019.csv']

In [5]:
df = pd.DataFrame()
for i in range(0, len(matches) - 1):
    df_1 = pd.read_csv(path + matches[i], encoding='utf8')
    df_2 = pd.read_csv(path + matches[i + 1], encoding='utf8')
    partial = df_1.append(df_2)
    df = df.append(partial)

df

8   NaN
9   NaN
10  NaN
11  NaN
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
10  NaN
11  NaN
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
10  NaN
11  NaN
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
10  NaN
11  NaN
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
10  NaN
11  NaN
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
10  NaN
11  NaN

    P7 - Rede Pluvial (trimestral)
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
0   6.60
1  NaN
2  NaN
3   1.20
4  NaN
5  NaN
6   5.40
7  NaN
8  NaN
9   0.42
10 NaN
11 NaN
0   6.60
1  NaN
2  NaN
3   1.20
4  NaN
5  NaN
6   5.40
7  NaN
8  NaN
9   0.42
10 NaN
11 NaN
0   4.50
1  NaN
2  NaN
3   7.70
4  NaN
5  NaN
6   1.90
7  NaN
8  NaN
9   0.19
10 NaN
11 NaN
0   4.50
1  NaN
2  NaN
3   7.70
4  NaN
5  NaN
6   1.90
7  NaN
8  NaN
9   0.19
10 NaN
11 NaN
0   0.90
1  NaN
2  NaN
3   1.90
4  NaN
5  NaN
6   6.50
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
0   0.90
1  NaN
2  NaN
3   1.90
4  NaN
5  NaN
6   6.50
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
0  NaN
1  NaN
2  NaN
3   12.70
4  NaN
5  NaN
6   2.10
7  NaN
8  NaN
9   3.80
10 NaN
11 NaN
0  NaN
1  NaN
2  NaN
3   12.70
4  NaN
5  NaN
6   2.10
7  NaN
8  NaN
9   3.80
10 NaN
11 NaN
0   0.70
1  NaN
2  NaN
3   13.21
4  NaN
5  NaN
6   18.20
7  NaN
8  NaN
9   1.60
10 NaN
11 NaN

In [28]:
df.to_csv(f"./Merged/{word}.csv", encoding='utf8', index=False)
copy2("cleaner.ipynb", f"./Logs/{word}.ipynb")

'./Logs/DQO.ipynb'