In [1]:
import numpy as np 
import pandas as pd 
from os import listdir
from shutil import copy2 

# Pandas setup
pd.set_option('display.max_columns', 1000)
pd.set_option('display.max_rows', 1000) 
pd.set_option('display.max_colwidth', -1)

In [13]:
path = "./Dataset/"
word = "surfactantes"
archives = listdir(path) 

matches = [value for value in archives if word in value]
matches = sorted(matches)
matches

['surfactantes_2013.csv',
 'surfactantes_2014.csv',
 'surfactantes_2015.csv',
 'surfactantes_2016.csv',
 'surfactantes_2017.csv',
 'surfactantes_2018.csv',
 'surfactantes_2019.csv']

In [16]:
df = pd.DataFrame()
for i in range(0, len(matches) - 1):
    df_1 = pd.read_csv(path + matches[i], encoding='utf8')
    df_2 = pd.read_csv(path + matches[i + 1], encoding='utf8')
    partial = df_1.append(df_2)
    df = df.append(partial)

df

8   NaN
9   NaN
10  NaN
11  NaN
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
10  NaN
11  NaN
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
10  NaN
11  NaN
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
10  NaN
11  NaN
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
10  NaN
11  NaN
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
10  NaN
11  NaN

   P7 - Rede Pluvial Portão A
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
10  NaN
11  NaN
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
10  NaN
11  NaN
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
10  NaN
11  NaN
0   0.47
1   NaN
2   NaN
3   0.64
4   NaN
5   NaN
6   0.2
7   NaN
8   NaN
9   0.1
10  NaN
11  NaN
0   0.47
1   NaN
2   NaN
3   0.64
4   NaN
5   NaN
6   0.2
7   NaN
8   NaN
9   0.1
10  NaN
11  NaN
0   0.1
1   NaN
2   NaN
3   0.1
4   NaN
5   NaN
6   0.12
7   NaN
8   NaN
9   <0,10
10  NaN
11  NaN
0   0.1
1   NaN
2   NaN
3   0.1
4   NaN
5   NaN
6   0.12
7   NaN
8   NaN
9   <0,10
10  NaN
11  NaN
0   0.22
1   NaN
2   NaN
3   <0,1
4   NaN
5   NaN
6   1.16
7   NaN
8   NaN
9   NaN
10  NaN
11  NaN
0   0.22
1   NaN
2   NaN
3   <0,1
4   NaN
5   NaN
6   1.16
7   NaN
8   NaN
9   NaN
10  NaN
11  NaN
0   NaN
1   NaN
2   NaN
3   8.7
4   NaN
5   NaN
6   0.16
7   NaN
8   NaN
9   4.55
10  NaN
11  NaN
0   NaN
1   NaN
2   NaN
3   8.7
4   NaN
5   NaN
6   0.16
7   NaN
8   NaN
9   4.55
10  NaN
11  NaN
0   0.38
1   NaN
2   NaN
3   3.48
4   NaN
5   NaN
6   7.2
7   NaN
8   NaN
9   0.14
10  NaN
11  NaN

In [17]:
df.to_csv(f"./Merged/{word}.csv", encoding='utf8', index=False)
copy2("cleaner.ipynb", f"./Logs/{word}.ipynb")

'./Logs/surfactantes.ipynb'